#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 09 18:56:36 CET 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim TB_TOP_BLINK_behav -key {Behavioral:sim_1:Functional:TB_TOP_BLINK} -tclbatch TB_TOP_BLINK.tcl -view /home/roberto/Desktop/roberto/CLOCK_ALLARM1.0/TB_TOP_MODE_behav.wcfg -log simulate.log"
xsim TB_TOP_BLINK_behav -key {Behavioral:sim_1:Functional:TB_TOP_BLINK} -tclbatch TB_TOP_BLINK.tcl -view /home/roberto/Desktop/roberto/CLOCK_ALLARM1.0/TB_TOP_MODE_behav.wcfg -log simulate.log

